name: pytest

on:
  push: # run on every push or PR to any branch
  
jobs:
  python-unit:
    name: pytest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run pytest
        run: pytest
